tf.placeholder : Put data in here
    ex) sess.run(tf.placeholder(...), feed_dict=[...])
tf.Variable : Variables we want to know

In [ ]:
import tensorflow as tf

In [3]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, cost_val, hy_val)

0 86994.36 [ -97.93656  -138.20915  -125.672295 -137.55023  -109.69044 ]
10 77.51812 [162.82974 175.27655 183.17723 198.78267 129.43323]
20 76.3101 [163.585   176.24818 184.10138 199.79254 130.18733]
30 75.90005 [163.55367 176.27422 184.09393 199.78792 130.22014]
40 75.49194 [163.52002 176.29733 184.08366 199.78023 130.2507 ]
50 75.08631 [163.48647 176.32034 184.07344 199.77254 130.28116]
60 74.6827 [163.45299 176.3433  184.06319 199.76483 130.31151]
70 74.28149 [163.41963 176.36621 184.05301 199.7572  130.3418 ]
80 73.88221 [163.38634 176.38905 184.04283 199.74957 130.37201]
90 73.485306 [163.35318 176.41183 184.03273 199.74199 130.40216]
100 73.09038 [163.32007 176.43454 184.0226  199.73439 130.4322 ]
110 72.697586 [163.28703 176.4572  184.01251 199.72679 130.46214]
120 72.306984 [163.25412 176.4798  184.00247 199.71925 130.49203]
130 71.91854 [163.2213  176.50233 183.99245 199.71173 130.52184]
140 71.532104 [163.18857 176.52481 183.98245 199.70422 130.55157]
150 71.14787 [163.15591 

1370 36.93116 [159.77055 178.87137 182.93944 198.9163  133.6592 ]
1380 36.733833 [159.74721 178.8874  182.93233 198.91087 133.68048]
1390 36.537476 [159.7239  178.90343 182.92522 198.90549 133.7017 ]
1400 36.342243 [159.70067 178.91937 182.91812 198.9001  133.72287]
1410 36.147972 [159.67749 178.9353  182.91107 198.89471 133.74399]
1420 35.954945 [159.65439 178.95116 182.90402 198.88937 133.76503]
1430 35.762703 [159.63133 178.96698 182.89697 198.88399 133.78604]
1440 35.571667 [159.60834 178.98276 182.88995 198.87865 133.80696]
1450 35.381638 [159.58542 178.9985  182.883   198.87332 133.82785]
1460 35.19267 [159.56258 179.0142  182.87602 198.86806 133.8487 ]
1470 35.004658 [159.53976 179.02986 182.86906 198.86273 133.86945]
1480 34.817654 [159.51704 179.04549 182.86214 198.85747 133.89018]
1490 34.63163 [159.49434 179.06105 182.85521 198.85219 133.91083]
1500 34.446686 [159.47174 179.07658 182.84833 198.84694 133.93144]
1510 34.262688 [159.44917 179.09206 182.84143 198.84167 133.95198

In [6]:
x_data = [
    [73., 80., 75.],
    [93., 88., 93.],
    [89., 91., 90.],
    [96., 98., 100.],
    [73., 66., 70.],
]
y_data = [
    [152.],
    [185.],
    [180.],
    [196.],
    [142.],
]
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [10]:
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, cost_val, "\n", hy_val)

0 2259.3608 
 [[103.06634 ]
 [138.67664 ]
 [128.90565 ]
 [140.2031  ]
 [109.867165]]
10 21.991158 
 [[144.9267 ]
 [188.95535]
 [178.46397]
 [194.16895]
 [148.21025]]
20 21.852848 
 [[145.0714 ]
 [189.09508]
 [178.61943]
 [194.33629]
 [148.30992]]
30 21.735676 
 [[145.08984]
 [189.08316]
 [178.62541]
 [194.34088]
 [148.29395]]
40 21.619091 
 [[145.10786]
 [189.07079]
 [178.63092]
 [194.34496]
 [148.27766]]
50 21.503162 
 [[145.12582]
 [189.05847]
 [178.63641]
 [194.34904]
 [148.26141]]
60 21.38783 
 [[145.14372]
 [189.04619]
 [178.64189]
 [194.3531 ]
 [148.24518]]
70 21.273182 
 [[145.16158]
 [189.03392]
 [178.64732]
 [194.3571 ]
 [148.229  ]]
80 21.159052 
 [[145.17941]
 [189.0217 ]
 [178.65279]
 [194.36116]
 [148.21289]]
90 21.045654 
 [[145.19717]
 [189.00952]
 [178.65823]
 [194.36519]
 [148.19682]]
100 20.93278 
 [[145.2149 ]
 [188.99736]
 [178.66364]
 [194.3692 ]
 [148.18079]]
110 20.82053 
 [[145.23257]
 [188.98523]
 [178.66905]
 [194.37321]
 [148.1648 ]]
120 20.708902 
 [[145.250

1090 12.310407 
 [[146.7511 ]
 [187.94333]
 [179.13315]
 [194.71803]
 [146.78989]]
1100 12.244758 
 [[146.76459]
 [187.93404]
 [179.13727]
 [194.7211 ]
 [146.77763]]
1110 12.179522 
 [[146.77805]
 [187.9248 ]
 [179.14137]
 [194.72415]
 [146.76543]]
1120 12.114561 
 [[146.79147]
 [187.91557]
 [179.14546]
 [194.7272 ]
 [146.75323]]
1130 12.050003 
 [[146.80487]
 [187.90639]
 [179.14957]
 [194.73026]
 [146.7411 ]]
1140 11.985764 
 [[146.81824]
 [187.89722]
 [179.15366]
 [194.7333 ]
 [146.729  ]]
1150 11.9218645 
 [[146.83157]
 [187.88808]
 [179.15771]
 [194.73636]
 [146.71693]]
1160 11.858363 
 [[146.84485]
 [187.87897]
 [179.1618 ]
 [194.73938]
 [146.7049 ]]
1170 11.795171 
 [[146.85811]
 [187.86989]
 [179.16585]
 [194.7424 ]
 [146.69289]]
1180 11.732315 
 [[146.87132]
 [187.86081]
 [179.16988]
 [194.7454 ]
 [146.68091]]
1190 11.669787 
 [[146.8845 ]
 [187.85176]
 [179.17389]
 [194.74841]
 [146.66896]]
1200 11.607615 
 [[146.89763]
 [187.84273]
 [179.1779 ]
 [194.75139]
 [146.65703]]
121