In [16]:
import tensorflow as tf
import numpy as np

In [14]:
x_data = [
    [1, 2, 1],
    [1, 3, 2],
    [1, 3, 4],
    [1, 5, 5],
    [1, 7, 5],
    [1, 2, 5],
    [1, 6, 6],
    [1, 7, 7],
]
y_data = [
    [0, 0, 1],
    [0, 0, 1],
    [0, 0, 1],
    [0, 1, 0],
    [0, 1, 0],
    [0, 1, 0],
    [1, 0, 0],
    [1, 0, 0]
]
x_test = [
    [2, 1, 1],
    [3, 1, 2],
    [3, 3, 4]
]
y_test = [
    [0, 0, 1],
    [0, 0, 1],
    [0, 0, 1]
]
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost)
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [15]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                     feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    print("Accuracy:", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 4.039287 [[-0.7986747   0.3633462   0.72395426]
 [ 0.3533412   1.9682024   0.46550867]
 [ 0.20337589 -0.11129545 -0.1957373 ]]
1 4.039287 [[-0.7986747   0.3633462   0.72395426]
 [ 0.3533412   1.9682024   0.46550867]
 [ 0.20337589 -0.11129545 -0.1957373 ]]
2 4.039287 [[-0.7986747   0.3633462   0.72395426]
 [ 0.3533412   1.9682024   0.46550867]
 [ 0.20337589 -0.11129545 -0.1957373 ]]
3 4.039287 [[-0.7986747   0.3633462   0.72395426]
 [ 0.3533412   1.9682024   0.46550867]
 [ 0.20337589 -0.11129545 -0.1957373 ]]
4 4.039287 [[-0.7986747   0.3633462   0.72395426]
 [ 0.3533412   1.9682024   0.46550867]
 [ 0.20337589 -0.11129545 -0.1957373 ]]
5 4.039287 [[-0.7986747   0.3633462   0.72395426]
 [ 0.3533412   1.9682024   0.46550867]
 [ 0.20337589 -0.11129545 -0.1957373 ]]
6 4.039287 [[-0.7986747   0.3633462   0.72395426]
 [ 0.3533412   1.9682024   0.46550867]
 [ 0.20337589 -0.11129545 -0.1957373 ]]
7 4.039287 [[-0.7986747   0.3633462   0.72395426]
 [ 0.3533412   1.9682024   0.46550867]
 [ 0.203

158 4.039287 [[-0.7986747   0.3633462   0.72395426]
 [ 0.3533412   1.9682024   0.46550867]
 [ 0.20337589 -0.11129545 -0.1957373 ]]
159 4.039287 [[-0.7986747   0.3633462   0.72395426]
 [ 0.3533412   1.9682024   0.46550867]
 [ 0.20337589 -0.11129545 -0.1957373 ]]
160 4.039287 [[-0.7986747   0.3633462   0.72395426]
 [ 0.3533412   1.9682024   0.46550867]
 [ 0.20337589 -0.11129545 -0.1957373 ]]
161 4.039287 [[-0.7986747   0.3633462   0.72395426]
 [ 0.3533412   1.9682024   0.46550867]
 [ 0.20337589 -0.11129545 -0.1957373 ]]
162 4.039287 [[-0.7986747   0.3633462   0.72395426]
 [ 0.3533412   1.9682024   0.46550867]
 [ 0.20337589 -0.11129545 -0.1957373 ]]
163 4.039287 [[-0.7986747   0.3633462   0.72395426]
 [ 0.3533412   1.9682024   0.46550867]
 [ 0.20337589 -0.11129545 -0.1957373 ]]
164 4.039287 [[-0.7986747   0.3633462   0.72395426]
 [ 0.3533412   1.9682024   0.46550867]
 [ 0.20337589 -0.11129545 -0.1957373 ]]
165 4.039287 [[-0.7986747   0.3633462   0.72395426]
 [ 0.3533412   1.9682024   0.46

In [17]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [20]:
def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

xy = MinMaxScaler(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  5.122214 
Prediction:
 [[3.7113476]
 [4.4953547]
 [3.20588  ]
 [1.7762766]
 [2.5817213]
 [2.5394866]
 [1.1031953]
 [1.5169454]]
1 Cost:  5.121834 
Prediction:
 [[3.7112348]
 [4.4952435]
 [3.205788 ]
 [1.776206 ]
 [2.5816371]
 [2.5394053]
 [1.1031411]
 [1.5168912]]
2 Cost:  5.121454 
Prediction:
 [[3.711122 ]
 [4.4951324]
 [3.2056954]
 [1.7761353]
 [2.5815532]
 [2.539324 ]
 [1.1030867]
 [1.5168372]]
3 Cost:  5.1210737 
Prediction:
 [[3.7110095]
 [4.495021 ]
 [3.2056034]
 [1.7760648]
 [2.581469 ]
 [2.539243 ]
 [1.1030325]
 [1.5167831]]
4 Cost:  5.1206937 
Prediction:
 [[3.7108967]
 [4.49491  ]
 [3.2055116]
 [1.7759941]
 [2.5813851]
 [2.5391614]
 [1.1029782]
 [1.5167291]]
5 Cost:  5.1203136 
Prediction:
 [[3.710784 ]
 [4.4947987]
 [3.2054193]
 [1.7759236]
 [2.5813012]
 [2.5390804]
 [1.1029239]
 [1.516675 ]]
6 Cost:  5.119934 
Prediction:
 [[3.7106717]
 [4.4946876]
 [3.2053275]
 [1.775853 ]
 [2.5812173]
 [2.5389993]
 [1.1028696]
 [1.516621 ]]
7 Cost:  5.1195545 
Prediction:
 [[3.7