In [1]:
import tensorflow as tf

In [11]:
x_data = [
    [1, 2, 1, 1],
    [2, 1, 3, 2],
    [3, 1, 3, 4],
    [4, 1, 5, 5],
    [1, 7, 5, 5],
    [1, 2, 5, 6],
    [1, 6, 6, 6],
    [1, 7, 7, 7]
]
y_data = [
    [0, 0, 1],
    [0, 0, 1],
    [0, 0, 1],
    [0, 1, 0],
    [0, 1, 0],
    [0, 1, 0],
    [1, 0, 0],
    [1, 0, 0]
]
nb_classes = 3
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))
            
    all = sess.run(hypothesis, feed_dict={X: [
        [1, 11, 7, 9],
        [1, 3, 4, 3],
        [1, 1, 0, 1]
        ]})
    print(all, sess.run(tf.arg_max(all, 1)))

0 2.2480683
200 0.50880617
400 0.41812038
600 0.3441894
800 0.2713582
1000 0.22834226
1200 0.20721938
1400 0.18959366
1600 0.17465568
1800 0.16183619
2000 0.15071893
[[2.7492978e-03 9.9724030e-01 1.0390222e-05]
 [8.9384240e-01 9.2226677e-02 1.3930917e-02]
 [1.1327957e-08 3.2816693e-04 9.9967182e-01]] [1 0 2]
