np.array[xrange, yrange] : xrange,yrange: 1:3 // [2,4,5]
tf.matmul(X, W)
tf.reduce_mean(tf.square(tf.matmul(X, W) + b) - Y)


In [1]:
import numpy as np
import tensorflow as tf

In [2]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
xy

array([[ 73.,  80.,  75., 152.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.],
       [ 53.,  46.,  55., 101.]], dtype=float32)

In [3]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [4]:
tf.set_random_seed(777)

In [5]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict={X: x_data, Y: y_data}
    )
    if step % 10 == 0:
        print(step, cost_val, '\n', hy_val)

0 20344.273 
 [[22.048063 ]
 [21.619787 ]
 [24.096693 ]
 [22.293005 ]
 [18.633902 ]
 [ 7.2669735]]
10 7.591933 
 [[154.9885 ]
 [181.46912]
 [181.56465]
 [193.78198]
 [140.56638]
 [ 97.16199]]
20 6.624332 
 [[155.87779]
 [182.55698]
 [182.62657]
 [194.94084]
 [141.39882]
 [ 97.78158]]
30 6.5896964 
 [[155.8728 ]
 [182.56958]
 [182.62921]
 [194.9461 ]
 [141.41107]
 [ 97.79651]]
40 6.5553193 
 [[155.86182]
 [182.5749 ]
 [182.62471]
 [194.9436 ]
 [141.41779]
 [ 97.80733]]
50 6.521196 
 [[155.85083]
 [182.58017]
 [182.62018]
 [194.94107]
 [141.42441]
 [ 97.81806]]
60 6.487265 
 [[155.83986]
 [182.5854 ]
 [182.61565]
 [194.9385 ]
 [141.43102]
 [ 97.82877]]
70 6.4535728 
 [[155.82895]
 [182.59062]
 [182.61115]
 [194.93599]
 [141.4376 ]
 [ 97.83946]]
80 6.4200826 
 [[155.81807 ]
 [182.59584 ]
 [182.60664 ]
 [194.93347 ]
 [141.44417 ]
 [ 97.850105]]
90 6.386806 
 [[155.80719]
 [182.60101]
 [182.60217]
 [194.93097]
 [141.4507 ]
 [ 97.86071]]
100 6.3537693 
 [[155.79639]
 [182.60619]
 [182.59769]

1140 3.8659031 
 [[154.84608]
 [183.05841]
 [182.20389]
 [194.7145 ]
 [142.0214 ]
 [ 98.80561]]
1150 3.8491716 
 [[154.83842]
 [183.06203]
 [182.20068]
 [194.71283]
 [142.02585]
 [ 98.81319]]
1160 3.8325937 
 [[154.83081]
 [183.06563]
 [182.1975 ]
 [194.71114]
 [142.03029]
 [ 98.82073]]
1170 3.8161056 
 [[154.82321 ]
 [183.06921 ]
 [182.19434 ]
 [194.7095  ]
 [142.0347  ]
 [ 98.828255]]
1180 3.7997415 
 [[154.81566]
 [183.07281]
 [182.19121]
 [194.70789]
 [142.03911]
 [ 98.83575]]
1190 3.783448 
 [[154.80812 ]
 [183.07639 ]
 [182.18806 ]
 [194.70625 ]
 [142.04352 ]
 [ 98.843254]]
1200 3.7672985 
 [[154.80058 ]
 [183.07993 ]
 [182.18494 ]
 [194.7046  ]
 [142.04787 ]
 [ 98.850685]]
1210 3.7512245 
 [[154.7931  ]
 [183.08348 ]
 [182.1818  ]
 [194.70299 ]
 [142.05225 ]
 [ 98.858116]]
1220 3.7352428 
 [[154.7856 ]
 [183.08702]
 [182.1787 ]
 [194.70137]
 [142.05658]
 [ 98.86551]]
1230 3.7194045 
 [[154.77818 ]
 [183.09053 ]
 [182.17558 ]
 [194.69977 ]
 [142.06091 ]
 [ 98.872894]]
1240 3.7036

In [7]:
print(sess.run(hypothesis, feed_dict={X: [[100, 79, 101]]}))

[[180.44875]]


In [8]:
print(sess.run(hypothesis, feed_dict={X: [[60, 70, 110],[90, 100, 80]]}))

[[106.725494]
 [197.8313  ]]


In [23]:
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

(<tf.Tensor 'ReaderReadV2_4:0' shape=() dtype=string>,
 <tf.Tensor 'ReaderReadV2_4:1' shape=() dtype=string>)

In [37]:
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [50]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
coord = tf.train.Coordinator()

In [51]:
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Field 0 in record 0 is not a valid float: # EXAM1
	 [[Node: DecodeCSV_4 = DecodeCSV[OUT_TYPE=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], field_delim=",", na_value="", select_cols=[], use_quote_delim=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ReaderReadV2:1, DecodeCSV_4/record_defaults_0, DecodeCSV_4/record_defaults_0, DecodeCSV_4/record_defaults_0, DecodeCSV_4/record_defaults_0)]]


In [28]:
for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict={X: x_batch, Y: y_batch}
    )
    if step % 10 == 0:
        print(step, cost_val, '\n', hy_val)
        
coord.request_stop()
coord.join(threads)

OutOfRangeError: FIFOQueue '_85_batch_6/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[Node: batch_6 = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch_6/fifo_queue, batch_6/n)]]

Caused by op 'batch_6', defined at:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 1431, in _run_once
    handle._run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-25-ee4fbc341f76>", line 3, in <module>
    train_x_batch, train_y_batch =     tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 988, in batch
    name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 762, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 483, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3480, in queue_dequeue_many_v2
    component_types=component_types, timeout_ms=timeout_ms, name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): FIFOQueue '_85_batch_6/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[Node: batch_6 = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch_6/fifo_queue, batch_6/n)]]
