# Softmax Classification

In [4]:
import numpy as np 
import tensorflow as tf

In [1]:
# feature 4개짜리 데이터 8개
x_data = [[1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5], 
         [1,2,5,6], [1,6,6,6], [1,7,7,7]]
#3 class -> 한데이터당 y값 3개 + one-hot encoding
y_data= [[0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0], [1,0,0], [1,0,0]]

In [7]:
x_data

[[1, 2, 1, 1],
 [2, 1, 3, 2],
 [3, 1, 3, 4],
 [4, 1, 5, 5],
 [1, 7, 5, 5],
 [1, 2, 5, 6],
 [1, 6, 6, 6],
 [1, 7, 7, 7]]

In [9]:
y_data

[[0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0]]

In [19]:
X = tf.placeholder('float', [None, 4])
Y = tf.placeholder('float', [None, 3]) # class의 갯수가 y의 column
nb_classes = 3

In [27]:
# W의 각 컬럼이 각 class에 대한 h(x)만듬
W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')

#b는 nb_classes 짜리 벡터
b = tf.Variable(tf.random_normal([nb_classes]), name='bias') 


In [28]:
hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)

In [29]:
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

In [30]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [35]:
sess= tf.Session()

In [36]:

sess.run(tf.global_variables_initializer())

for step in range(2001):
    sess.run(optimizer, feed_dict={X:x_data, Y: y_data})
    if step % 200 ==0:
        print(step, sess.run(cost, feed_dict={X:x_data, Y: y_data}))

0 3.928839
200 0.54314166
400 0.45358112
600 0.3808045
800 0.31119126
1000 0.2427854
1200 0.21724698
1400 0.19836238
1600 0.1823844
1800 0.16870078
2000 0.15685871


### 새로운 값 던져주고 찾고 싶을 때 

In [38]:
a = sess.run(hypothesis, feed_dict ={X: [[1, 11, 7, 9], [1,3,4,3], [1,1,0,1]]})
print(a, sess.run(tf.argmax(a, 1))) # 어떤 놈이 가장 큰놈인가요? 알려주는게 arg_max


[[1.2521732e-02 9.8746777e-01 1.0517810e-05]
 [7.7525514e-01 1.9486335e-01 2.9881479e-02]
 [1.3460642e-08 3.4776345e-04 9.9965227e-01]] [1 0 2]
