# Multi-Variable Linear Regression

In [4]:
import tensorflow as tf

In [14]:
x1_data = [73., 93., 90., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data= [75., 93., 90., 100., 70]
y_data = [152., 185., 180., 196., 142]

In [15]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

In [16]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [22]:
hypothesis = x1*w1 + x2*w2 + x3*w3 + b

In [23]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [24]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train= optimizer.minimize(cost)

In [28]:
sess = tf.Session()

In [29]:
sess.run(tf.global_variables_initializer())

In [30]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                  feed_dict ={x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  28501.34 
Prediction:
 [1.4529219  4.677272   1.7033644  7.58755    0.44767278]
10 Cost:  8.466138 
Prediction:
 [150.65047 184.01799 179.05663 200.00621 137.24548]
20 Cost:  8.200519 
Prediction:
 [151.09181 184.55649 179.58595 200.57872 137.65892]
30 Cost:  8.189156 
Prediction:
 [151.08882 184.56087 179.58708 200.57817 137.66496]
40 Cost:  8.177836 
Prediction:
 [151.08449 184.56364 179.58662 200.5759  137.66977]
50 Cost:  8.166573 
Prediction:
 [151.0802  184.5664  179.58621 200.57365 137.67458]
60 Cost:  8.155352 
Prediction:
 [151.07593 184.56918 179.58577 200.5714  137.67935]
70 Cost:  8.144155 
Prediction:
 [151.07166 184.57195 179.58534 200.56915 137.68414]
80 Cost:  8.133051 
Prediction:
 [151.06741 184.57469 179.58492 200.56693 137.6889 ]
90 Cost:  8.121912 
Prediction:
 [151.06317 184.57744 179.5845  200.56468 137.69368]
100 Cost:  8.110898 
Prediction:
 [151.05894 184.58018 179.58408 200.56245 137.69841]
110 Cost:  8.099862 
Prediction:
 [151.0547  184.5829  179.5

1150 Cost:  7.149859 
Prediction:
 [150.67708 184.82632 179.55188 200.34431 138.14058]
1160 Cost:  7.1422515 
Prediction:
 [150.67401 184.82832 179.55167 200.34239 138.14433]
1170 Cost:  7.134754 
Prediction:
 [150.67093 184.83032 179.5515  200.34048 138.14804]
1180 Cost:  7.1272264 
Prediction:
 [150.66785 184.83229 179.55128 200.33855 138.15175]
1190 Cost:  7.119745 
Prediction:
 [150.66478 184.83429 179.55112 200.33664 138.15546]
1200 Cost:  7.1122675 
Prediction:
 [150.66174 184.83626 179.55092 200.33473 138.15916]
1210 Cost:  7.104828 
Prediction:
 [150.65869 184.83823 179.55074 200.33281 138.16284]
1220 Cost:  7.0974135 
Prediction:
 [150.65567 184.8402  179.55055 200.33092 138.16653]
1230 Cost:  7.0900145 
Prediction:
 [150.65263 184.84215 179.55037 200.329   138.1702 ]
1240 Cost:  7.0826583 
Prediction:
 [150.6496  184.84406 179.55016 200.32707 138.17384]
1250 Cost:  7.0753145 
Prediction:
 [150.64659 184.84601 179.54999 200.32516 138.17749]
1260 Cost:  7.0679865 
Prediction:
 

# Use Matrix!

In [53]:
# rank 2 , 5X3 Matrix, 1row = 1 instance
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90], [96., 98., 100.], [73., 66., 70.]]
# rank 2, 5*1 Matrix
y_data = [[152.],[185.], [180.], [196.], [142.]]

In [54]:
# None means 'Whatever you want'
#None of X row or Y row -> 데이터 몇개이를 던지든 상관없음
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

In [43]:
W = tf.Variable(tf.random_normal([3,1]), name="Weight")
b = tf.Variable(tf.random_normal([1]), name = "bias")

In [44]:
# matmul -> matmultiply
hypothesis = tf.matmul(X, W)+b

In [49]:
#cost function
cost= tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [50]:
sess = tf.Session()

In [51]:
sess.run(tf.global_variables_initializer())

In [52]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict = {X:x_data, Y:y_data})
    if step % 10 ==0:
        print(step, "Cost:", cost_val, "\nPrediction\n", hy_val)

0 Cost: 5111.0005 
Prediction
 [[219.53767]
 [257.7501 ]
 [257.2678 ]
 [277.82254]
 [197.09854]]
10 Cost: 8.594274 
Prediction
 [[156.33734]
 [181.80907]
 [182.43082]
 [196.32848]
 [139.17865]]
20 Cost: 8.503817 
Prediction
 [[156.135  ]
 [181.58691]
 [182.20094]
 [196.07968]
 [139.01315]]
30 Cost: 8.460339 
Prediction
 [[156.12328]
 [181.5938 ]
 [182.1968 ]
 [196.0767 ]
 [139.02237]]
40 Cost: 8.417076 
Prediction
 [[156.11215]
 [181.60138]
 [182.19336]
 [196.0745 ]
 [139.03207]]
50 Cost: 8.374052 
Prediction
 [[156.10109]
 [181.60893]
 [182.18993]
 [196.07228]
 [139.0418 ]]
60 Cost: 8.331234 
Prediction
 [[156.09004]
 [181.6165 ]
 [182.18651]
 [196.07007]
 [139.05145]]
70 Cost: 8.288701 
Prediction
 [[156.07903]
 [181.62401]
 [182.18309]
 [196.06789]
 [139.06108]]
80 Cost: 8.2463665 
Prediction
 [[156.06805]
 [181.63152]
 [182.1797 ]
 [196.0657 ]
 [139.07072]]
90 Cost: 8.204222 
Prediction
 [[156.05708]
 [181.639  ]
 [182.1763 ]
 [196.0635 ]
 [139.0803 ]]
100 Cost: 8.162397 
Predictio

940 Cost: 5.3417892 
Prediction
 [[155.22543]
 [182.2068 ]
 [181.9185 ]
 [195.8999 ]
 [139.80617]]
950 Cost: 5.3153253 
Prediction
 [[155.21674]
 [182.21274]
 [181.9158 ]
 [195.89822]
 [139.81374]]
960 Cost: 5.2890244 
Prediction
 [[155.20807]
 [182.21866]
 [181.91313]
 [195.89655]
 [139.82129]]
970 Cost: 5.2627974 
Prediction
 [[155.1994 ]
 [182.22458]
 [181.91043]
 [195.89488]
 [139.82881]]
980 Cost: 5.2367716 
Prediction
 [[155.19078]
 [182.23047]
 [181.90776]
 [195.8932 ]
 [139.83632]]
990 Cost: 5.21087 
Prediction
 [[155.18219]
 [182.23634]
 [181.90509]
 [195.89154]
 [139.84383]]
1000 Cost: 5.1850886 
Prediction
 [[155.17358]
 [182.2422 ]
 [181.90242]
 [195.88986]
 [139.85127]]
1010 Cost: 5.159433 
Prediction
 [[155.16502]
 [182.24806]
 [181.89975]
 [195.88823]
 [139.85872]]
1020 Cost: 5.133954 
Prediction
 [[155.15648]
 [182.25388]
 [181.8971 ]
 [195.88658]
 [139.86613]]
1030 Cost: 5.1085887 
Prediction
 [[155.14795]
 [182.25969]
 [181.89445]
 [195.88492]
 [139.87354]]
1040 Cost:

1920 Cost: 3.3207421 
Prediction
 [[154.47424]
 [182.7192 ]
 [181.68497]
 [195.75684]
 [140.45679]]
1930 Cost: 3.3050969 
Prediction
 [[154.46753]
 [182.72375]
 [181.68289]
 [195.75562]
 [140.46259]]
1940 Cost: 3.289575 
Prediction
 [[154.46086]
 [182.7283 ]
 [181.6808 ]
 [195.75435]
 [140.46834]]
1950 Cost: 3.274131 
Prediction
 [[154.4542 ]
 [182.73285]
 [181.67874]
 [195.75311]
 [140.47406]]
1960 Cost: 3.2587514 
Prediction
 [[154.44756]
 [182.73738]
 [181.67667]
 [195.75189]
 [140.4798 ]]
1970 Cost: 3.243457 
Prediction
 [[154.4409 ]
 [182.74188]
 [181.6746 ]
 [195.75064]
 [140.4855 ]]
1980 Cost: 3.2282548 
Prediction
 [[154.4343 ]
 [182.74638]
 [181.67255]
 [195.74942]
 [140.4912 ]]
1990 Cost: 3.2131417 
Prediction
 [[154.42772]
 [182.75089]
 [181.67049]
 [195.7482 ]
 [140.49686]]
2000 Cost: 3.1981072 
Prediction
 [[154.42116]
 [182.75537]
 [181.66844]
 [195.74698]
 [140.50252]]
