# Loading Data from File

In [1]:
import numpy as np

In [2]:
xy = np.loadtxt('data/data-01-test-score.csv', delimiter=",", dtype=np.float32)

In [3]:
xy

array([[ 73.,  80.,  75., 152.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.],
       [ 53.,  46.,  55., 101.],
       [ 69.,  74.,  77., 149.],
       [ 47.,  56.,  60., 115.],
       [ 87.,  79.,  90., 175.],
       [ 79.,  70.,  88., 164.],
       [ 69.,  70.,  73., 141.],
       [ 70.,  65.,  74., 141.],
       [ 93.,  95.,  91., 184.],
       [ 79.,  80.,  73., 152.],
       [ 70.,  73.,  78., 148.],
       [ 93.,  89.,  96., 192.],
       [ 78.,  75.,  68., 147.],
       [ 81.,  90.,  93., 183.],
       [ 88.,  92.,  86., 177.],
       [ 78.,  83.,  77., 159.],
       [ 82.,  86.,  90., 177.],
       [ 86.,  82.,  89., 175.],
       [ 78.,  83.,  85., 175.],
       [ 76.,  83.,  71., 149.],
       [ 96.,  93.,  95., 192.]], dtype=float32)

In [4]:
x_data = xy[:, 0:-1] #행 전체, 열은 첫번째부터 마지막 바로 전까지
y_data = xy[:, [-1]] # 행 전체, 열은 마지막만

In [5]:
print(x_data.shape, x_data, len(x_data))

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25


In [6]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)

/Users/sanghyuk/anaconda/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [7]:
xy = np.loadtxt('data/data-01-test-score.csv', delimiter=",", dtype=np.float32)
x_data = xy[:, 0:-1] #행 전체, 열은 첫번째부터 마지막 바로 전까지
y_data = xy[:, [-1]] # 행 전체, 열은 마지막만

In [8]:
X = tf.placeholder(tf.float32, shape=[None, 3]) 
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [9]:
W = tf.Variable(tf.random_normal([3, 1]), name="weight")
b = tf.Variable(tf.random_normal([1]), name= 'bias')

In [10]:
hypothesis = tf.matmul(X, W)+b

In [11]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [12]:
#Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate= 1e-5)
train = optimizer.minimize(cost)

In [13]:
sess =tf.Session()

In [14]:
sess.run(tf.global_variables_initializer())

In [15]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y:y_data})
    if step%10 ==0:
        print(step, "Cost :", cost_val, "\nPrediction : \n", hy_val)


0 Cost : 21027.0 
Prediction : 
 [[22.048063 ]
 [21.619787 ]
 [24.096693 ]
 [22.293005 ]
 [18.633902 ]
 [ 7.2669735]
 [12.33103  ]
 [ 3.150511 ]
 [14.347944 ]
 [ 4.2534237]
 [14.485708 ]
 [10.678068 ]
 [28.80464  ]
 [29.298803 ]
 [11.237837 ]
 [18.646544 ]
 [31.189451 ]
 [13.344664 ]
 [28.841742 ]
 [25.66281  ]
 [15.084761 ]
 [16.798368 ]
 [15.924551 ]
 [31.36112  ]
 [24.986364 ]]
10 Cost : 95.97634 
Prediction : 
 [[157.11063]
 [183.99281]
 [184.06302]
 [196.52917]
 [142.46274]
 [ 98.59757]
 [142.77235]
 [ 99.8778 ]
 [166.13176]
 [144.8915 ]
 [140.14995]
 [134.61139]
 [194.05147]
 [166.64041]
 [142.28706]
 [183.43298]
 [161.97667]
 [169.89073]
 [186.37146]
 [166.61377]
 [168.04634]
 [169.14368]
 [161.75204]
 [167.48862]
 [193.25117]]
20 Cost : 94.25726 
Prediction : 
 [[158.01503 ]
 [185.11975 ]
 [185.15112 ]
 [197.73497 ]
 [143.315   ]
 [ 99.26257 ]
 [143.69464 ]
 [100.587845]
 [167.21953 ]
 [145.9485  ]
 [141.02908 ]
 [135.50377 ]
 [195.15509 ]
 [167.5308  ]
 [143.2218  ]
 [184.5926

450 Cost : 68.38536 
Prediction : 
 [[156.90688]
 [185.31175]
 [184.48805]
 [197.82817]
 [143.16753]
 [100.59033]
 [144.54968]
 [102.27448]
 [168.74892]
 [149.30394]
 [141.4697 ]
 [136.92343]
 [193.66113]
 [165.22446]
 [144.39871]
 [185.4241 ]
 [160.09781]
 [172.18953]
 [185.62549]
 [165.92896]
 [170.05737]
 [171.09753]
 [163.29839]
 [165.34859]
 [193.97816]]
460 Cost : 67.887764 
Prediction : 
 [[156.88373 ]
 [185.31526 ]
 [184.47395 ]
 [197.83006 ]
 [143.16371 ]
 [100.61787 ]
 [144.56805 ]
 [102.310814]
 [168.78056 ]
 [149.37427 ]
 [141.47897 ]
 [136.95302 ]
 [193.6294  ]
 [165.17545 ]
 [144.42374 ]
 [185.44125 ]
 [160.03986 ]
 [172.21521 ]
 [185.58766 ]
 [165.89487 ]
 [170.07722 ]
 [171.1157  ]
 [163.30975 ]
 [165.28522 ]
 [193.96873 ]]
470 Cost : 67.39422 
Prediction : 
 [[156.86067 ]
 [185.31871 ]
 [184.45987 ]
 [197.83197 ]
 [143.1599  ]
 [100.64526 ]
 [144.58632 ]
 [102.347015]
 [168.81207 ]
 [149.44429 ]
 [141.48819 ]
 [136.98248 ]
 [193.59776 ]
 [165.1266  ]
 [144.44865 ]
 [18

920 Cost : 48.950756 
Prediction : 
 [[155.93658 ]
 [185.44363 ]
 [183.88834 ]
 [197.91473 ]
 [142.98041 ]
 [101.745705]
 [145.35065 ]
 [103.859   ]
 [170.07724 ]
 [152.28574 ]
 [141.86855 ]
 [138.17322 ]
 [192.30612 ]
 [163.12654 ]
 [145.47913 ]
 [186.14333 ]
 [157.60405 ]
 [173.31732 ]
 [184.01613 ]
 [164.48285 ]
 [170.91963 ]
 [171.86067 ]
 [163.79948 ]
 [162.65569 ]
 [193.5621  ]]
930 Cost : 48.61406 
Prediction : 
 [[155.91838]
 [185.44576]
 [183.87689]
 [197.91652]
 [142.97626]
 [101.76744]
 [145.36641]
 [103.89014]
 [170.1022 ]
 [152.34247]
 [141.87627]
 [138.1969 ]
 [192.28012]
 [163.08618]
 [145.50012]
 [186.15685]
 [157.55579]
 [173.33965]
 [183.98538]
 [164.45534]
 [170.9365 ]
 [171.87502]
 [163.80946]
 [162.6043 ]
 [193.55383]]
940 Cost : 48.280155 
Prediction : 
 [[155.90027 ]
 [185.44789 ]
 [183.86551 ]
 [197.91827 ]
 [142.97214 ]
 [101.789055]
 [145.38211 ]
 [103.921165]
 [170.12706 ]
 [152.39896 ]
 [141.88396 ]
 [138.22047 ]
 [192.25426 ]
 [163.046   ]
 [145.52103 ]
 [1

1380 Cost : 36.006073 
Prediction : 
 [[155.18916 ]
 [185.51883 ]
 [183.41168 ]
 [197.99324 ]
 [142.78659 ]
 [102.638916]
 [146.02528 ]
 [105.191284]
 [171.10368 ]
 [154.64478 ]
 [142.19484 ]
 [139.15378 ]
 [191.2181  ]
 [161.43202 ]
 [146.36842 ]
 [186.69954 ]
 [155.5663  ]
 [174.279   ]
 [182.73387 ]
 [163.33873 ]
 [171.63776 ]
 [172.45262 ]
 [164.23117 ]
 [160.51408 ]
 [193.2052  ]]
1390 Cost : 35.77535 
Prediction : 
 [[155.1748 ]
 [185.51997]
 [183.40236]
 [197.99489]
 [142.78232]
 [102.65609]
 [146.03888]
 [105.2181 ]
 [171.12341]
 [154.69073]
 [142.20131]
 [139.17279]
 [191.19673]
 [161.39862]
 [146.38615]
 [186.71025]
 [155.52588]
 [174.2985 ]
 [182.70877]
 [163.31645]
 [171.65215]
 [172.46405]
 [164.23997]
 [160.47224]
 [193.19794]]
1400 Cost : 35.54654 
Prediction : 
 [[155.16055 ]
 [185.5211  ]
 [183.3931  ]
 [197.99654 ]
 [142.77805 ]
 [102.67318 ]
 [146.05243 ]
 [105.244835]
 [171.14305 ]
 [154.7365  ]
 [142.20776 ]
 [139.19171 ]
 [191.17546 ]
 [161.36537 ]
 [146.4038  ]
 

1880 Cost : 26.489067 
Prediction : 
 [[154.55716]
 [185.55536]
 [182.99362]
 [198.07173]
 [142.57187]
 [103.39739]
 [146.65466]
 [106.43207]
 [171.97482]
 [156.70293]
 [142.49023]
 [140.00107]
 [190.25291]
 [159.91896]
 [147.17873]
 [187.17209]
 [153.72385]
 [175.1872 ]
 [181.60614]
 [162.34052]
 [172.30011]
 [172.95737]
 [164.64293]
 [158.63457]
 [192.86621]]
1890 Cost : 26.335304 
Prediction : 
 [[154.54616 ]
 [185.55571 ]
 [182.98618 ]
 [198.07324 ]
 [142.56758 ]
 [103.410645]
 [146.66626 ]
 [106.45491 ]
 [171.99002 ]
 [156.73944 ]
 [142.49557 ]
 [140.01602 ]
 [190.23561 ]
 [159.89172 ]
 [147.19347 ]
 [187.18033 ]
 [153.69049 ]
 [175.20403 ]
 [181.58603 ]
 [162.3228  ]
 [172.31226 ]
 [172.96619 ]
 [164.6506  ]
 [158.6011  ]
 [192.85991 ]]
1900 Cost : 26.182732 
Prediction : 
 [[154.53522]
 [185.55605]
 [182.97874]
 [198.07472]
 [142.5633 ]
 [103.42381]
 [146.67783]
 [106.47769]
 [172.00514]
 [156.7758 ]
 [142.50093]
 [140.0309 ]
 [190.21838]
 [159.86464]
 [147.20816]
 [187.18854]
 

In [16]:
#Ask my Score

In [17]:
# feed dict n, 3을 줘야함. 
print("Your score will be ", sess.run(hypothesis, feed_dict={X:[[100, 70, 100]]}))

Your score will be  [[181.40741]]


# Queue Runners

In [18]:
filename_queue = tf.train.string_input_producer(['data/data-01-test-score.csv'],
                                               shuffle=False, name="filename_queue")

In [19]:
reader = tf.TextLineReader() #문자열 한줄씩 읽어서 리턴
key, value = reader.read(filename_queue) #value에 읽은 값이 순차적으로 리턴됨

In [20]:

#각각의 field에 해당하는 값이 어떤 데이터 타입인지!
#reder에서 읽은 값은 아직 raw 데이터임. 
#데이터를 파싱하는 컴포넌트가 Decoder

#각 필드의 디폴트값 + 데이터 타입인지 지정함. 
# ex) "null"로 했으면, default는 null이고, data type은 string
record_defaults = [[0.], [0.], [0.], [0.]]
# csv
xy = tf.decode_csv(value, record_defaults= record_defaults)

In [28]:
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10 )
#펌프질 한번마다 10개씩 가지고 오라는게 batch_size임

In [34]:
X = tf.placeholder(tf.float32, shape=[None, 3]) 
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name="weight")
b = tf.Variable(tf.random_normal([1]), name= 'bias')


In [35]:
hypothesis = tf.matmul(X, W)+b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [36]:
#Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate= 1e-5)
train = optimizer.minimize(cost)

In [37]:
sess= tf.Session()

In [38]:
sess.run(tf.global_variables_initializer())

In [39]:
# 통상적으로 쓰는 코드
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord= coord)

In [40]:
for step in range(2001):
    x_batch, y_batch= sess.run([train_x_batch, train_y_batch]) #펌프질 해서 뽑아오는 것
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict = {X:x_batch, Y:y_batch})
    if step %10 ==0:
        print(step, "Cost:", cost_val, "Prediction", hy_val)

0 Cost: 63014.645 Prediction [[ -93.44802 ]
 [ -97.77742 ]
 [-104.20064 ]
 [ -73.790184]
 [ -80.69573 ]
 [ -83.424805]
 [ -77.125984]
 [-111.1882  ]
 [ -78.468834]
 [ -91.865166]]
10 Cost: 57.9073 Prediction [[183.17772]
 [179.14153]
 [143.64471]
 [149.52646]
 [179.25449]
 [144.87953]
 [151.71474]
 [192.41222]
 [138.11229]
 [176.91267]]
20 Cost: 63.94123 Prediction [[184.98329]
 [180.78241]
 [145.1709 ]
 [151.00214]
 [181.29321]
 [146.58769]
 [153.3009 ]
 [194.39641]
 [139.7364 ]
 [178.82437]]
30 Cost: 63.478992 Prediction [[184.95049]
 [180.72054]
 [145.17484]
 [150.97682]
 [181.32944]
 [146.6312 ]
 [153.29984]
 [194.38443]
 [139.77507]
 [178.83997]]
40 Cost: 62.956383 Prediction [[184.90533]
 [180.64738]
 [145.16841]
 [150.94144]
 [181.35193]
 [146.66318]
 [153.28801]
 [194.35898]
 [139.8028 ]
 [178.84267]]
50 Cost: 62.43815 Prediction [[184.8603 ]
 [180.57451]
 [145.16197]
 [150.90614]
 [181.37424]
 [146.69496]
 [153.2762 ]
 [194.33354]
 [139.8303 ]
 [178.84529]]
60 Cost: 61.92452 P

650 Cost: 38.54458 Prediction [[182.48584]
 [176.75067]
 [144.82803]
 [149.05032]
 [182.53514]
 [148.34361]
 [152.67169]
 [192.99263]
 [141.24132]
 [179.0151 ]]
660 Cost: 38.245884 Prediction [[182.45125]
 [176.69528]
 [144.82327]
 [149.02336]
 [182.55183]
 [148.3672 ]
 [152.6632 ]
 [192.9731 ]
 [141.26122]
 [179.01811]]
670 Cost: 37.94997 Prediction [[182.41681]
 [176.64017]
 [144.81854]
 [148.99655]
 [182.56844]
 [148.3907 ]
 [152.65477]
 [192.95366]
 [141.28104]
 [179.02113]]
680 Cost: 37.65661 Prediction [[182.38252]
 [176.58527]
 [144.81383]
 [148.96982]
 [182.58493]
 [148.41405]
 [152.64636]
 [192.93428]
 [141.30074]
 [179.02412]]
690 Cost: 37.366005 Prediction [[182.34839]
 [176.53064]
 [144.80916]
 [148.94325]
 [182.6014 ]
 [148.43732]
 [152.63803]
 [192.91501]
 [141.32034]
 [179.02716]]
700 Cost: 37.077827 Prediction [[182.31438]
 [176.47621]
 [144.80449]
 [148.91676]
 [182.61775]
 [148.46045]
 [152.62971]
 [192.89583]
 [141.33983]
 [179.03015]]
710 Cost: 36.792408 Prediction 

1300 Cost: 23.788284 Prediction [[180.52063]
 [173.62228]
 [144.56406]
 [147.52423]
 [183.46938]
 [149.65982]
 [152.20802]
 [191.8834 ]
 [142.33577]
 [179.21649]]
1310 Cost: 23.62202 Prediction [[180.49448]
 [173.58093]
 [144.56065]
 [147.50401]
 [183.4816 ]
 [149.67696]
 [152.20215]
 [191.86867]
 [142.34976]
 [179.21967]]
1320 Cost: 23.457235 Prediction [[180.46844]
 [173.53976]
 [144.55725]
 [147.48387]
 [183.49377]
 [149.694  ]
 [152.1963 ]
 [191.85397]
 [142.36368]
 [179.22282]]
1330 Cost: 23.293854 Prediction [[180.44249]
 [173.49876]
 [144.55386]
 [147.46379]
 [183.50584]
 [149.71095]
 [152.19048]
 [191.83931]
 [142.37749]
 [179.22597]]
1340 Cost: 23.132065 Prediction [[180.41669]
 [173.458  ]
 [144.5505 ]
 [147.44383]
 [183.51791]
 [149.72786]
 [152.18471]
 [191.82477]
 [142.39125]
 [179.22914]]
1350 Cost: 22.971645 Prediction [[180.39096]
 [173.41737]
 [144.54715]
 [147.42397]
 [183.52989]
 [149.74464]
 [152.17894]
 [191.81026]
 [142.40494]
 [179.23228]]
1360 Cost: 22.812687 Pr

1920 Cost: 15.848528 Prediction [[179.09306]
 [171.37941]
 [144.38243]
 [146.42372]
 [184.12633]
 [150.5765 ]
 [151.90112]
 [191.07814]
 [143.07095]
 [179.41245]]
1930 Cost: 15.753244 Prediction [[179.07298]
 [171.3481 ]
 [144.37996]
 [146.40831]
 [184.13539]
 [150.5891 ]
 [151.89703]
 [191.0668 ]
 [143.08083]
 [179.41557]]
1940 Cost: 15.658777 Prediction [[179.053  ]
 [171.31693]
 [144.37749]
 [146.39296]
 [184.14442]
 [150.60161]
 [151.89297]
 [191.05554]
 [143.09065]
 [179.41872]]
1950 Cost: 15.56518 Prediction [[179.03308]
 [171.28589]
 [144.37505]
 [146.37767]
 [184.1534 ]
 [150.61407]
 [151.88893]
 [191.04431]
 [143.1004 ]
 [179.42183]]
1960 Cost: 15.472415 Prediction [[179.01328]
 [171.25499]
 [144.3726 ]
 [146.36247]
 [184.16234]
 [150.62646]
 [151.88493]
 [191.03314]
 [143.11012]
 [179.42499]]
1970 Cost: 15.38048 Prediction [[178.99353]
 [171.22424]
 [144.37018]
 [146.34732]
 [184.17123]
 [150.6388 ]
 [151.88094]
 [191.02202]
 [143.11977]
 [179.42812]]
1980 Cost: 15.289357 Pre

In [41]:
coord.request_stop()
coord.join(threads)