우리가 가지고 있는 데이터셋을 Training 과 Test datasets로 나눈다

In [3]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]


# 아래의 test 데이터는 전혀 사용하지 않고 있다가 나중에 Test
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [8]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

#W 에서 row는 각 feature에 곱해지는 애들이고, 
# column은 3가지 class에 매칭
W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

In [10]:
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [12]:
prediction = tf.arg_max(hypothesis, 1)
is_correct= tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [13]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                     feed_dict= {X: x_data, Y: y_data})
        print(step, cost_val, W_val)
        
    #predict 여기서는 test data 던지는 것
    print("Prediction", sess.run(prediction, feed_dict= {X: x_test}))
    print("Accuracy: ", sess.run(accuracy, feed_dict= {X: x_test, Y: y_test}))

0 4.3388414 [[ 1.2355698   0.47824878 -0.37337106]
 [ 0.0346016   0.85286474  0.28761488]
 [-0.2098035  -0.6323289  -0.14723438]]
1 2.3339381 [[ 1.2550209   0.42634806 -0.34092137]
 [ 0.1815628   0.6236158   0.36990267]
 [-0.07039869 -0.83612853 -0.08283959]]
2 1.4961228 [[ 1.245046    0.42448962 -0.32908815]
 [ 0.19281897  0.64150554  0.34075674]
 [-0.07663148 -0.7844271  -0.12830822]]
3 1.4613702 [[ 1.2357184   0.41400617 -0.30927706]
 [ 0.20588563  0.61387867  0.35531694]
 [-0.08182859 -0.7769784  -0.1305598 ]]
4 1.4407952 [[ 1.2252864   0.40684912 -0.291688  ]
 [ 0.21273743  0.6041822   0.35816163]
 [-0.09210534 -0.7531466  -0.14411482]]
5 1.4221735 [[ 1.2160988   0.39812657 -0.2737779 ]
 [ 0.22526155  0.58669966  0.36312005]
 [-0.09602204 -0.7377723  -0.15557246]]
6 1.4042327 [[ 1.2061276   0.390323   -0.25600326]
 [ 0.23310964  0.5743225   0.3676491 ]
 [-0.10390276 -0.7183321  -0.16713189]]
7 1.3868539 [[ 1.1967846   0.3819724  -0.23830967]
 [ 0.24351966  0.55947626  0.37208536]


## Learning Rate: NaN!

In [14]:
# 위 코드에서 Learning rate 를 1.5나, 10으로 해봐
#지나치게 크게 하면 발사될 수 있고, 
#지나치게 작게 하면 매우 조금씩 작아짐. 

## Normalize Data

In [15]:
# feature의 값들이 너무 지나치게 크면 한쪽 방향으로 치우치는 등고선 그래프가 나옴. 
# 잘 내려가기가 어려움. 

MinmaxScalar(xy)
값을 넣으면, 새로운 값을 리턴해줌.
제일 작은값을 0, 제일 큰값을 1로 두고 그 사이의 값들을
리턴해줌

> 등고선이 매우 기울어진 원에서 멀쩡한 원이 됨. 
> 데이터가 매우 크거나 들쭉날쭉할떄는 반드시 normalize를 할것. 