reshape, squeeze, expane

In [3]:
import tensorflow as tf

In [4]:
sess = tf.Session()

In [5]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval(session=sess)

array([4], dtype=int32)

In [6]:
t = tf.constant([[1,2],[3,4]])
tf.shape(t).eval(session=sess)

array([2, 2], dtype=int32)

In [7]:
tf.shape(t).eval(session=sess)

array([2, 2], dtype=int32)

In [8]:
matrix1 = tf.constant([[1,2],[3,4]])
matrix2 = tf.constant([[3,4],[5,6]])
tf.matmul(matrix1, matrix2).eval(session=sess)

array([[13, 16],
       [29, 36]], dtype=int32)

In [9]:
matrix1 = tf.constant([[3.,3.]])
matrix2 = tf.constant([[2.,2.]])
(matrix1 + matrix2).eval(session=sess)

array([[5., 5.]], dtype=float32)

In [10]:
tf.reduce_mean([1,2],axis=0).eval(session=sess)

1

In [12]:
x = [[1,2],[3,4]]
tf.reduce_mean(x, axis=0).eval(session=sess)

array([2, 3], dtype=int32)

In [13]:
t = [[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]]
tf.reshape(t, shape=[-1,3]).eval(session=sess)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int32)

In [14]:
t = tf.one_hot([[0],[1],[2],[0]], depth=3).eval(session=sess)

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [15]:
tf.reshape(t, shape=[-1,3]).eval(session=sess)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int32)