# Tensor Manipulation

In [1]:
import numpy as np

### 1차원

In [2]:
# 1차원 array
t = np.array([0., 1., 2., 3., 4., 5., 6])

In [4]:
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [5]:
print(t.ndim) #rank

1


In [6]:
print(t.shape)

(7,)


In [9]:
print(t[0], t[1], t[-1])

0.0 1.0 6.0


In [10]:
print(t[2:5], t[4:-1])

[2. 3. 4.] [4. 5.]


In [11]:
print(t[:2], t[3:])

[0. 1.] [3. 4. 5. 6.]


### 2차원

In [13]:
t = np.array([[1.,2.,3.], [4.,5.,6.], [7.,8.,9], [10.,11.,12]])

In [14]:
print(t.ndim)

2


In [15]:
print(t.shape)

(4, 3)


In [16]:
t

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

# Tensorflow

In [18]:
import tensorflow as tf

In [23]:
t = tf.constant([1,2,3,4])

In [33]:
sess= tf.Session()

In [97]:
#앞에 있는 괄호 숫자가 rank 임
tf.shape(t).eval(session=sess)

array([4, 1, 3], dtype=int32)

In [35]:
t = tf.constant([[1,2], [3,4]])
tf.shape(t).eval(session=sess)

array([2, 2], dtype=int32)

shape 볼때, 일단 괄호타고 제일 끝까지 들어가서 부터 시작하는 것.

#### Axis -> 제일 안쪽부터 시작, 0부터 시작 <br>
4차원이면 제일 안쪽꺼부터 axis=3
그 바로 앞단이 axis=2
axis=1
axis=0 순으로

In [37]:
matrix1 = tf.constant([[1.,2.], [3.,4.]])
matrix2 = tf.constant([[1.], [2.]])

In [40]:
matrix1.shape
matrix2.shape

TensorShape([Dimension(2), Dimension(1)])

In [41]:
tf.matmul(matrix1, matrix2).eval(session =sess)

array([[ 5.],
       [11.]], dtype=float32)

matrix 하지 않고 * 하면 다른 값이 나옴. <br>
의도적으로 하지 않고 실수로 하면 큰일남. 

#### broadcasting

In [42]:
matrix1 = tf.constant([[3.,3.]])
matrix2 = tf.constant([[2.,2.]])

In [44]:
(matrix1+matrix2).eval(session=sess)
#같은 shape이니깐 1:1로 매핑해서 나옴. 

array([[5., 5.]], dtype=float32)

그러나 shape이 다르더라도 연산이 되버림<br>
ex)<br>
1x2 와 3 을 더하는데 3이 찢어져서 양쪽에 들어가. <br>
서로 아예 다른 형태여도 앞에꺼 뒤에꺼가 같이 extend들어가면서 <br>
연산이 막 됨.


#### Reduce Mean

In [47]:
tf.reduce_mean([1,2], axis=0).eval(session=sess)
#1이 나오는 이유, 지금 [1,2]가 integer이기 떄문.
#rank가 2니깐 axis는 0과 1이 있겠지. 
#그 중에 제일 바깥꺼 부터 0부터 시작. 

#축을 쓰면 축끼리 하는거고, 축 안쓰면 element 전체 다임. 

1

In [98]:
x = [[1.,2.], [3.,4.]]
tf.reduce_mean(x, axis=0).eval(session=sess)

array([2., 3.], dtype=float32)

In [100]:
tf.reduce_mean(x, axis=1).eval(session=sess)

array([1.5, 3.5], dtype=float32)

In [101]:
tf.reduce_mean(x, axis=-1).eval(session=sess)

array([1.5, 3.5], dtype=float32)

In [102]:
tf.reduce_sum(x, axis= 0).eval(session=sess)

array([4., 6.], dtype=float32)

In [103]:
tf.reduce_sum(x, axis= 1).eval(session=sess)

array([3., 7.], dtype=float32)

In [104]:
# 제일 안쪽꺼 

#### Argmax

In [57]:
x = [[0,1,2],
    [2,1,0]]

In [105]:
tf.argmax(x, axis=0).eval(session=sess)

array([1, 1])

In [106]:
tf.argmax(x, axis=1).eval(session=sess)

array([1, 1])

In [107]:
tf.argmax(x, axis=-1).eval(session=sess)

array([1, 1])

#### Reshape (매우중요)

In [108]:
t = np.array([[[0, 1, 2], [3,4,5]], [[6,7,8], [9,10,11]]])

In [109]:
t.shape

(2, 2, 3)

In [71]:
tf.reshape(t, shape=[-1, 3]).eval(session=sess)
# rank는 -1과 3 두개, 맨안에꺼는 3개 그 바로 바깥꺼는 너 알아서 하렴~

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [72]:
tf.reshape(t, shape=[-1, 1, 3]).eval(session=sess)

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [73]:
# Reshape(squeeze, expand)
# squeeze 는 쭉 펴줌. 


In [75]:
tf.squeeze([[0], [1], [2]]).eval(session=sess)

array([0, 1, 2], dtype=int32)

In [77]:
# expand_dims 는 앞의 어레이에 뒤에 얼마만큼의 디멘션을 추가할껀지 쓰는 것.

tf.expand_dims([0, 1, 2], 1).eval(session=sess)

array([[0],
       [1],
       [2]], dtype=int32)

#### One Hot

1, 2, 3, 4가 있으면<br>
지금 class가 총 4개니깐, 4개짜리 vector 만들고, 그 자리에만 1넣고 나머지는 0 넣음

In [80]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval(session=sess)

#근데 결과 보면 지금 rank가 3개야. 
#상관없어 reshape해주면 됨. 

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [83]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval(session=sess)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

#### Casting

In [85]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval(session=sess) #integer로 바꿔줌

array([1, 2, 3, 4], dtype=int32)

In [86]:
tf.cast([True, False,1==1, 0==1], tf.int32).eval(session=sess)
#true를 1로, false를 0으로 바꿔줌 

array([1, 0, 1, 0], dtype=int32)

#### Stack

쌓아줌. 

In [88]:
x= [1,4]
y= [2,5]
z = [3,6]

tf.stack([x, y, z]).eval(session=sess)

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [89]:
tf.stack([x, y, z], axis=1).eval(session=sess)
# 축을 바꾸면서 쌓는 방법을 바꿈 기본으로 쌓은 다음에 axis=1

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

#### Ones and Zeros like

행렬을 주면 그거와 똑같은 모양의 <br>
0 혹은 1로 채워진 행렬을 리턴해줌

In [90]:
x= [[0,1,2], [2,1,0]]

In [91]:
tf.ones_like(x).eval(session=sess)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [93]:
tf.zeros_like(x).eval(session=sess)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

#### Zip

In [94]:
for x, y in zip([1,2,3], [4,5,6]):
    print(x, y)

1 4
2 5
3 6


In [95]:
for x, y, z in zip([1,2,3], [4,5,6], [7,8,9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
